# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170612_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.IntegerField(default=0, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(default='', max_length=100, verbose_name='Должность'),
        ),
    ]
