# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-04 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170621_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image', verbose_name='Фото'),
        ),
    ]
