# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 18:37
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('n', django.db.models.manager.Manager()),
            ],
        ),
    ]
